### ISSUE TITLE
Name doesn't fit patter

### ISSUE THREAD

**Issue by Hades32** [product-os/t-npm-builder#20]
We typically call them `t-FROM-to-TARGET`. Mind that when you rename the repo you need to
* create a PR after that
* delete all old Transformer version OR
* remove the "owns" link between the loop and the old Transformer repo
* create "owns" link from loop to new Transformer repo

**Comment by danthegoodman1** [comment]
@Hades32 I think to make things easy I will jsut copy the source code over to https://github.com/product-os/t-node-module-source-to-node-module

**Comment by danthegoodman1** [comment]
since that already exists

**Comment by Hades32** [comment]
Sure. Just make sure to do the cleanup anyway, so don't get confused later

**Comment by danthegoodman1** [comment]
Alright time for me to totally mess up all my hard work on this thing by changing the links... pray for me

**Comment by danthegoodman1** [comment]
Old TF deleted in JF, made pr to new one https://github.com/product-os/t-node-module-source-to-node-module/pull/2

**Comment by danthegoodman1** [comment]
New TF linked to loop in JF

**Comment by danthegoodman1** [comment]
Closing since TF code moved
