### ISSUE TITLE
no tests for the t-tester

### ISSUE THREAD

**Issue by Hades32** [product-os/t-npm-builder#9]

**Comment by danthegoodman1** [comment]
Working on this now

**Comment by danthegoodman1** [comment]
The issue i see right now is this:
![image](https://user-images.githubusercontent.com/17806508/146802589-f7e2c47b-92e6-40dd-92ae-d950917d2390.png)

Questions:
1. Why is this test complete (success)?

I see the issue with the build not being there and that has been fixed. But I think the tester should have failed the test in this case even though the test was not the issue... (`suiteSuccess` should not be `true`)
